services:
  2twin2clouds:
    volumes:
      - ./config.json:/config/config.json:ro
      - ./config_credentials.json:/config/config_credentials.json:ro
      - ./google-credentials.json:/config/gcp_credentials.json:ro

  3cloud-deployer:
    volumes:
      - ./config.json:/config/config.json:ro
      - ./config_credentials.json:/config/config_credentials.json:ro
      - ./gcp_credentials.json:/config/gcp_credentials.json:ro

  management-api:
    volumes:
      - ./config_credentials.json:/config/config_credentials.json:ro
      - ./gcp_credentials.json:/config/gcp_credentials.json:ro
    environment:
      - SEED_DATA=true
      - SEED_CREDENTIALS_FILE=/config/config_credentials.json
      - SEED_GCP_CREDENTIALS_FILE=/config/gcp_credentials.json
