services:
  2twin2clouds:
    environment:
      - ENABLE_LOCAL_CREDENTIAL_FILE_CHECKS=true
    volumes:
      - type: bind
        source: ./.secrets/local/config.json
        target: /config/config.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./.secrets/local/config_credentials.json
        target: /config/config_credentials.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./.secrets/local/google-credentials.json
        target: /config/gcp_credentials.json
        read_only: true
        bind:
          create_host_path: false

  3cloud-deployer:
    environment:
      - ENABLE_LOCAL_CREDENTIAL_FILE_CHECKS=true
    volumes:
      - type: bind
        source: ./.secrets/local/config.json
        target: /config/config.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./.secrets/local/config_credentials.json
        target: /config/config_credentials.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./.secrets/local/gcp_credentials.json
        target: /config/gcp_credentials.json
        read_only: true
        bind:
          create_host_path: false

  management-api:
    volumes:
      - type: bind
        source: ./.secrets/local/config_credentials.json
        target: /config/config_credentials.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./.secrets/local/gcp_credentials.json
        target: /config/gcp_credentials.json
        read_only: true
        bind:
          create_host_path: false
    environment:
      - SEED_DATA=true
      - SEED_CREDENTIALS_FILE=/config/config_credentials.json
      - SEED_GCP_CREDENTIALS_FILE=/config/gcp_credentials.json
