"""Closed-world runtime values shared by cost formulas and deployment selections."""

STANDARD_FUNCTION_DURATION_MS = 100
MOVER_FUNCTION_DURATION_MS = 5_000

AWS_STANDARD_LAMBDA_MEMORY_MB = 256
AWS_MOVER_LAMBDA_MEMORY_MB = 512

AZURE_FUNCTION_MEMORY_MB = 128

GCP_STANDARD_FUNCTION_MEMORY_MB = 256
GCP_MOVER_FUNCTION_MEMORY_MB = 512
GCP_FUNCTION_MIN_INSTANCES = 0
GCP_STANDARD_FUNCTION_MAX_INSTANCES = 10
GCP_MOVER_FUNCTION_MAX_INSTANCES = 1
